name: Create SBOM

on: [push]

jobs:
  create-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Generate SBOM
        run: snyk wizard --generate-snyk-file
      - name: Commit SBOM
        uses: stefanzweifel/git-auto-commit-action@v4.1.0
        with:
          commit_message: "Update SBOM"
          file_pattern: "snyk.yml"
          branch: main
