name: Generate SBOM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download and install OWASP Dependency-Check
        run: |
          wget https://dl.bintray.com/jeremy-long/owasp/dependency-check-5.3.2.zip
          unzip dependency-check-5.3.2.zip
          chmod +x dependency-check/bin/dependency-check.sh
      - name: Generate SBOM
        run: dependency-check/bin/dependency-check.sh --project "My Project" --out "./sbom" --format "JSON" .
      - name: Create file in repository
        uses: actions/create-or-update-file@v4
        with:
          path: sbom/sbom.json
          content: ${{ toJson(file('./sbom/sbom.json')) }}
          message: "Add SBOM"
          branch: sbom
