on:
  push:
    branches: [ main, master ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install sbom
      run: |
        go get -u github.com/dpb587/bosh-dep-tool/sbom

    - name: Generate SBOM
      run: sbom -f json -i . -o sbom.json
    
